spring:
  application:
    name: currency-exchange
  datasource:
    url: jdbc:h2:mem:currency-exchange
  jpa:
    show-sql: true
    defer-datasource-initialization: true
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka