insert into CURRENCY_EXCHANGE(CONVERSION_MULTIPLE, ID, CURRENCY_FROM, CURRENCY_TO, ENVIRONMENT)
values (48000, 1001, 'USD', 'IRR', '');
insert into CURRENCY_EXCHANGE (CONVERSION_MULTIPLE, ID, CURRENCY_FROM, CURRENCY_TO, ENVIRONMENT)
values (70000, 1002, 'EUR', 'IRR', '');
insert into CURRENCY_EXCHANGE (CONVERSION_MULTIPLE, ID, CURRENCY_FROM, CURRENCY_TO, ENVIRONMENT)
values (25000, 1003, 'AUD', 'IRR', '');